//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientMonitorWatchApp.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientMonitorWatchApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PatientMonitorWatchApp.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PatientMonitorWatchApp.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to can not register the event.
        /// </summary>
        public static string ExceptionEventNotRegister
        {
            get
            {
                return ResourceManager.GetString("ExceptionEventNotRegister", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to can not unregister the event.
        /// </summary>
        public static string ExceptionEventNotUnregister
        {
            get
            {
                return ResourceManager.GetString("ExceptionEventNotUnregister", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Move page.
        /// </summary>
        public static string HeartbeatMonitorPageMoveButtonText {
            get {
                return ResourceManager.GetString("HeartbeatMonitorPageMoveButtonText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HeartbeatMonitor.
        /// </summary>
        public static string HeartbeatMonitorPageTitle {
            get {
                return ResourceManager.GetString("HeartbeatMonitorPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Show Popup.
        /// </summary>
        public static string RandomHealthInfoPageShowButtonText {
            get {
                return ResourceManager.GetString("RandomHealthInfoPageShowButtonText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Information Popup.
        /// </summary>
        public static string RandomHealthInfoPagePopupText {
            get {
                return ResourceManager.GetString("RandomHealthInfoPagePopupText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Information OK.
        /// </summary>
        public static string RandomHealthInfoPageOkButtonText {
            get {
                return ResourceManager.GetString("RandomHealthInfoPageOkButtonText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to RandomHealthInfo.
        /// </summary>
        public static string RandomHealthInfoPageTitle {
            get {
                return ResourceManager.GetString("RandomHealthInfoPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string WorkoutPageBottomText
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageBottomText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Bottom value.
        /// </summary>
        public static string WorkoutPageBottomValue
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageBottomValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string WorkoutPageLeftText
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageLeftText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left unit.
        /// </summary>
        public static string WorkoutPageLeftUnit
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageLeftUnit", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left value.
        /// </summary>
        public static string WorkoutPageLeftValue
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageLeftValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string WorkoutPageRightText
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageRightText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right unit.
        /// </summary>
        public static string WorkoutPageRightUnit
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageRightUnit", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right value.
        /// </summary>
        public static string WorkoutPageRightValue
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageRightValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string WorkoutPageTopText
        {
            get
            {
                return ResourceManager.GetString("WorkoutPageTopText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        public static string WorkoutPageTitle {
            get {
                return ResourceManager.GetString("WorkoutPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Updating is already started.
        /// </summary>
        public static string ExceptionLocationServiceAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionLocationServiceAlreadyStarted", resourceCulture);
            }
        }
    }
}
